### ISSUE TITLE
Command line

### ISSUE THREAD

**Issue by petrasvestartas** [danielTobon43/pointcloudToMesh#2]
Would it be possible to create command line interface for people with little coding knowledge?

**Comment by ghost** [comment]
Hi, what do you mean with the command line interface? 

To run this code you just need to open a terminal and then:

`./pointcloudToMESH <input cloud> <surface method estimation> <normal method estimation> <output dir>`

and I even put an example:

```
surface method estimation:
    1 --> for poisson
    2 --> for gp3
    
normal method estimation.
    1 --> for normal estimation
    2 --> for mls normal estimation
   ```

 example:
```
 ./pointcloudToMESH /home/xXx/cloud.txt 2 1 /home/xXx/Downloads   
```

**Comment by petrasvestartas** [comment]
The issue is that I have limited knowledge of C++ and have lots of problems installing the libraries (pcl).
I tried vtk installation, but it did not work, and could not find any good tutorials for dummies of pcl installation, let alone compilation.

Would it be possible to share 64bit Windows compiled version?

**Comment by ghost** [comment]
Oh I see. well, honestly this kind of question should be on the PCL community because is not related to my code, but anyway. I will tell you the way I use PCL so hopefully, you can understand more how to use it. 

Before that, I have never use PCL on windows just Ubuntu Linux 16.04 so, I don't know how to install PCL on windows. If you need PCL on windows I have a way to compile the library (without installing it), but again I don't know if will work well.

If you are using ubuntu I can tell you how to install PCL easily. So, please tell me what OS are you using?

**Comment by petrasvestartas** [comment]
I am using windows 64 bit, I would really like to test the compiled windows version from you.

**Comment by ghost** [comment]
Hi, i found this tutorial that in think is the best:
1. Download pcl all in one installer and cmake: 
https://github.com/PointCloudLibrary/pcl/releases/download/pcl-1.8.1/PCL-1.8.1-AllInOne-msvc2017-win64.exe
https://github.com/PointCloudLibrary/pcl/releases/download/pcl-1.8.1/pcl-1.8.1-pdb-msvc2017-win64.zip
https://github.com/Kitware/CMake/releases/download/v3.18.0/cmake-3.18.0-win64-x64.msi

2. Install pcl and cmake (not Qt):
https://www.youtube.com/watch?v=5nio-aeWp4I

3. compile and run a pcl example (you need visual studio):
https://www.youtube.com/watch?v=BR1fgnA_xAU&t=137s

I think this is the best solution for you
